### ISSUE TITLE
https://calver.org/ TLS certificate expired

### ISSUE THREAD

**Issue by mtbc** [mahmoud/calver#14]
> * SSL certificate problem: certificate has expired

**Comment by mtbc** [comment]
![expired](https://user-images.githubusercontent.com/2630707/54516530-12ecc500-4957-11e9-90b5-e8ef4cfb302e.png)

**Comment by mahmoud** [comment]
Ah jeez, thank you very very much for the report. Fixed! The post-mortem is that the autorenewal happened ok, but nginx didn't restart or reload the certs or something. I really need to update my certbot :P

Thanks again!
