### ISSUE TITLE
TLS Cert has expired

### ISSUE THREAD

**Issue by software-opal** [mahmoud/calver#19]
Hello from New Zealand,

The cert has expired as of about 3am. I presume it's a similar issue as #14 of the server not getting the new cert.

**Comment by mahmoud** [comment]
Good catch! This time it was because one of the domains on the cert expired (intentionally), but I didn't connect the dots that that would break the autorenewal here. Maybe I should shell out for some pagerduty or something. In any case, much appreciated!
