### ISSUE TITLE
TLS 1.0 deprecation

### ISSUE THREAD

**Issue by tdsmith** [mahmoud/calver#22]
Hi Mahmoud! A colleague at the next desk just noticed that https://calver.org throws up a security interstitial on Firefox Nightly because of the [forthcoming TLS ~1999.01~ 1.0 deprecation](https://hacks.mozilla.org/2019/05/tls-1-0-and-1-1-removal-update/). To keep the calver incantations secret and safe, would you mind upgrading to TLS ~2008.08~ 1.2? https://ssl-config.mozilla.org/ can help generate some config copypasta.

**Comment by mahmoud** [comment]
Good looking out! It took me a minute to get around to it, but the box is all rebuilt and the lock is looking good these days. Thanks again! :)
