### ISSUE TITLE
ECMAScript (a.k.a. "JavaScript") have been using CalVer since 2015

### ISSUE THREAD

**Issue by DrBenton** [mahmoud/calver#25]
See here for example: https://en.wikipedia.org/wiki/ECMAScript#Versions

Or there for the latest version: https://www.ecma-international.org/publications/standards/Ecma-262.htm
![Screenshot from 2020-01-20 11-25-01](https://user-images.githubusercontent.com/722388/72722988-967ad200-3b77-11ea-9f27-a003d2ed8fbd.png)

As a result it would likely deserve to be listed amongst the "Standards", wouldn't it? :slightly_smiling_face:

**Comment by mahmoud** [comment]
Good point! The lists are by no means complete, but that doesn't mean we can't get closer to completing them :) Good looking out, thanks!
