### ISSUE TITLE
Add internationalization support

### ISSUE THREAD

**Issue by networm** [mahmoud/calver#26]
I think it's better to have multiple languages translated. I just browse the folder structure and found nothing about internationalization. So could you add support for it?

I could translate it to Chinese Simplified.

**Comment by mahmoud** [comment]
Oooh, hen lihai! So, we could just add a zhongwen.md or something, and just translate [the overview](https://github.com/mahmoud/calver/blob/master/entries/overview.md). Would that work?

**Comment by networm** [comment]
It would not work because there are three pages need to be translated.
about.md overview.md users.md
I think it’s better that one folder per language. And  the generator need to support this and show a language menu or something similar.
For example you could take a look at https://semver.org

**Comment by networm** [comment]
Maybe Hugo is a choice for generating pages. It has template support and 1password official website is powered by Hugo.

**Comment by mahmoud** [comment]
I've seen the semver page more times than I care to recount. In my experience it's far from perfect; the Farsi localization is rendered in Arabic, for instance.

The about page is not really critical, and there's very little material text on the "Users" page, mostly numbers and links. Easy to add "中文" to the navigation. 

I think it'd be best to focus on content, and rearchitect once the number of translations proves to be unwieldy.

As far as content, I wouldn't worry about fully translating all the case studies, etc., we can start smaller. Maybe:

- Intro
- Scheme
- Case Study: Ubuntu
- Other notable projects (include non-translated case studies here as links)
- When to use CalVer

That should help narrow the scope and get us something usable faster.

**Comment by networm** [comment]
Ok, I will translate it to Chinese Simplified recently.

**Comment by mahmoud** [comment]
@networm any updates? hope all's well!

**Comment by networm** [comment]
Sorry for no updates, I have been too busy these days. I will translate it soon.
