### ISSUE TITLE
Docker Engine

### ISSUE THREAD

**Issue by linquize** [mahmoud/calver#29]
**Docker Engine** starting from **17.03** is calver-ed.
**1.13** and earlier versions are not.

**Comment by benmccallum** [comment]
And now it's going back on SemVer 😆
https://docs.docker.com/engine/release-notes/23.0/

**Comment by mahmoud** [comment]
@benmccallum that is hilarious. It's actually a notable case, in that regard. Unfortunately, the the DE's reasoning offloads most of the credit for the change to the golang folks. And it's pretty perfect for golang, they love oversimplifying things over there. [Not a lick of nuance in the golang doc](https://go.dev/doc/modules/version-numbers).
