### ISSUE TITLE
Can you explain the purpose of the Modifier. thanks

### ISSUE THREAD

**Issue by colomet** [mahmoud/calver#3]

**Comment by mahmoud** [comment]
Sure! Modifiers are a pretty common practice in versioning. A practical example: 

All my versions of [boltons](https://github.com/mahmoud/boltons) are CalVer with no modifier. However, the GitHub version's setup.py should always have a `dev` modifier. This way when someone reports a bug and their version has `dev` in it, I can tell they weren't using a release version, and I can respond accordingly (e.g., tell them to use a release version).

It's not at all specific to CalVer, but it's a very pragmatic pattern, and I encourage it :) Does that help?
