### ISSUE TITLE
Missing definition for two digit year with leading zero, 0Y

### ISSUE THREAD

**Issue by peterjc** [mahmoud/calver#5]
Under your convention I would expect ``0Y`` to be a two digit year with leading zero, e.g. year 2006 --> ``06`` and year 2016 -> ``16``.

It would be sensible to restrict this to 2000 to 2099 only to avoid ambiguity, or define year 2123 --> ``123`` here?

e.g. We could then describe this versioning scheme as ``MAJOR.0Y.0M.0D``:
https://ics.hutton.ac.uk/tablet/download-tablet/
https://ics.hutton.ac.uk/tablet/download-tablet/tablet-release-notes/

**Comment by mahmoud** [comment]
Pushed the update for this new terminology, thank you!
