### ISSUE TITLE
CalVer.org website is showing "ZeroVer: 0-based Versioning" instead CalVer documentation.

### ISSUE THREAD

**Issue by webmatrixxxl** [mahmoud/calver#57]
Starting from yesterday CalVer.org is showing wrong documentation. It is showing "ZeroVer: 0-based Versioning" instead of CalVer itself.

Internet Archive: [https://web.archive.org/web/20240412052808/https://calver.org/](https://web.archive.org/web/20240412052808/https://calver.org/)

<img width="1499" alt="image" src="https://github.com/mahmoud/calver/assets/3726238/ed1978a2-ba5c-4c4c-b4bb-1d6744b8c045">

**Comment by mahmoud** [comment]
Interesting, I'm guessing this is a DNS issue, as we've just switched registrars. I'm getting the correct calver.org site from multiple locations, so I'm thinking it's either a DNS cache issue, or potentially an IPv6 issue. I'll investigate, but if you have any more insight, do share. :)

**Comment by mahmoud** [comment]
Sure enough, there was an ipv6 directive for 0ver but not for calver, and when I copied over the DNS, I configured IPv6 on both. Give it a shot, it should be working now.
