### ISSUE TITLE
Remove `pytz`; replace with IANA Time Zone Database

### ISSUE THREAD

**Issue by Zac-HD** [mahmoud/calver#60]
The overview page prominently lists `pytz`:

https://github.com/mahmoud/calver/blob/f0ccce2ca238d3260a0ee7c1f4cfca1a3e99bdd8/entries/overview.md?plain=1#L160-L177

However, [`pytz` has serious compatibility issues](https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html) with [Python standards](https://peps.python.org/pep-0495/), and has largely been replaced by the [`zoneinfo` module in the standard library](https://docs.python.org/3/library/zoneinfo.html).  

I suggest minimally adapting this section to refer directly to [the tz database](https://data.iana.org/time-zones/tz-link.html), which describes the versioning scheme:

> Since 1996, each version has been a four-digit year followed by lower-case letter (a through z, then za through zz, then zza through zzz, and so on).

**Comment by mahmoud** [comment]
Hey Zac! That's a great idea. No special loyalty to pytz here. I'll make the change, unless you wanted to submit a PR.

**Comment by Zac-HD** [comment]
Sounds fun, I'll send you a PR tonight!
